Otter 51 researcher step 2
safeinsights/management-app pull request #41
Opened 2024-12-02 20:25 UTC by jbwilson8

[OTTER-51](https://openstax.atlassian.net/browse/OTTER-51)

![Screenshot 2024-12-02 at 2 24 38 PM](https://github.com/user-attachments/assets/e49d086b-17d6-4686-b8fc-4b2fec0bd4fd)

2024-12-02 23:00 UTC, nathanstitt requested changes

2024-12-02 23:00 UTC, nathanstitt commented on src/app/researcher/study/[encodedStudyId]/review/runs-table.tsx
>                                      {run.status == 'COMPLETED' && <PreviewCSVResultsBtn run={run} />}
we do not want to show the instructions after they've already uploaded their code, so we need to keep the `{run.status == 'INITIATED' && (`

2024-12-04 20:42 UTC, nathanstitt approved these changes

2024-12-04 20:43 UTC, therealmarv approved these changes

2024-12-11 21:51 UTC, jbwilson8 commented
After much diffing it looks like the only change that this PR would introduce is increasing the size of the "View Instructions" modal (`line 82`  in `runs-table.tsx` `size={800}`) The rest of the requirements for OTTER-51 are handled  in the [PR for OTTER-50](https://github.com/safeinsights/management-app/pull/35), the [PR for misc fixes for demo](https://github.com/safeinsights/management-app/pull/39), and [this PR](https://github.com/safeinsights/management-app/pull/37). I've created a [new PR](https://github.com/safeinsights/management-app/pull/45) (as discussed in this morning's sync) to accommodate this change and will make note of these things in the OTTER-51 jira card.

2024-12-11 21:51 UTC, closed without merging